// =============================================================================
// firmware-additions.h
//
// Companion for the Voltbench webpage. Adds:
//   1. Preferences (NVS) for all settings + saved Wi-Fi credentials
//   2. gzip-compressed PROGMEM HTML served with Content-Encoding: gzip
//   3. AsyncWebSocket push of /status (drops idle polling)
//   4. Optional bearer-token auth (X-Auth header)
//   5. Captive-portal AP fallback when no SSID can connect
//   6. Over-current / over-temperature guard with auto-recover
//   7. PubSubClient MQTT bridge
//
// Include this header AFTER the existing sketch globals (struct State, globals,
// read_VV_volt, setOutput, setVoltage) are defined.
// =============================================================================
#pragma once

#include <Preferences.h>
#include <ArduinoJson.h>
#include <ESPAsyncWebServer.h>
#include <AsyncJson.h>
#include <DNSServer.h>
#include <WiFi.h>
#include <esp_system.h>
#include <esp_random.h>
#include <PubSubClient.h>
#include <WiFiClient.h>

// Gzip-compressed index page (generated by PowerShell, see web_page.h)
extern const uint8_t  index_html_gz[]     PROGMEM;
extern const size_t   index_html_gz_len;

// Forward declarations — defined in the main sketch
extern AsyncWebServer server;
extern struct State   psState;
extern volatile uint32_t g_measured_mV;
extern volatile uint32_t g_setpoint_mV;
extern void setOutput(uint8_t output, bool state);
extern void setVoltage(float voltage);
extern int  read_VV_volt();
extern int  read_5V_volt();
extern int  read_3V3_volt();

// PID controller globals (defined in main sketch)
extern volatile float   g_pid_kp;
extern volatile float   g_pid_ki;
extern volatile float   g_pid_kd;
extern volatile uint8_t g_vctrl_state;
extern volatile bool    g_autotune_req;

// =============================================================================
//   Settings + persistent storage
// =============================================================================
struct VBSettings {
  String   mdns          = "voltbench";
  bool     require_login = true;
  String   password      = "admin";
  String   auth_token    = "";

  String   ota_url       = "https://updates.example.com/voltbench/";
  bool     ota_ssl       = true;
  bool     ota_auto      = true;

  bool     exp_current   = false;
  bool     exp_fast      = true;
  bool     exp_smooth    = false;
  bool     exp_dial      = false;

  bool     guard_ocp     = true;
  bool     guard_otp     = true;
  uint8_t  guard_otp_t   = 85;
  bool     guard_recover = false;

  float    ilim[3]       = {1.0f, 1.5f, 1.0f};
  bool     trip[3]       = {false, false, false};

  bool     mqtt_en       = false;
  String   mqtt_host     = "";
  uint16_t mqtt_port     = 1883;
  String   mqtt_user     = "";
  String   mqtt_pass     = "";
  String   mqtt_topic    = "voltbench";

  float    pid_kp        = 0.50f;
  float    pid_ki        = 0.10f;
  float    pid_kd        = 0.02f;
  bool     pid_tuned     = false;

  static const uint8_t MAX_SSID = 4;
  String   ssid[MAX_SSID];
  String   pass[MAX_SSID];
} vb;

Preferences vbPrefs;

void vb_load() {
  vbPrefs.begin("voltbench", true);
  vb.mdns          = vbPrefs.getString ("mdns",          vb.mdns);
  vb.require_login = vbPrefs.getBool   ("req_login",     vb.require_login);
  vb.password      = vbPrefs.getString ("password",      vb.password);
  vb.ota_url       = vbPrefs.getString ("ota_url",       vb.ota_url);
  vb.ota_ssl       = vbPrefs.getBool   ("ota_ssl",       vb.ota_ssl);
  vb.ota_auto      = vbPrefs.getBool   ("ota_auto",      vb.ota_auto);
  vb.exp_current   = vbPrefs.getBool   ("e_current",     vb.exp_current);
  vb.exp_fast      = vbPrefs.getBool   ("e_fast",        vb.exp_fast);
  vb.exp_smooth    = vbPrefs.getBool   ("e_smooth",      vb.exp_smooth);
  vb.exp_dial      = vbPrefs.getBool   ("e_dial",        vb.exp_dial);
  vb.guard_ocp     = vbPrefs.getBool   ("g_ocp",         vb.guard_ocp);
  vb.guard_otp     = vbPrefs.getBool   ("g_otp",         vb.guard_otp);
  vb.guard_otp_t   = vbPrefs.getUChar  ("g_otp_t",       vb.guard_otp_t);
  vb.guard_recover = vbPrefs.getBool   ("g_rec",         vb.guard_recover);
  for (int i = 0; i < 3; i++) vb.ilim[i] = vbPrefs.getFloat(("ilim" + String(i)).c_str(), vb.ilim[i]);
  vb.mqtt_en       = vbPrefs.getBool   ("mq_en",         vb.mqtt_en);
  vb.mqtt_host     = vbPrefs.getString ("mq_host",       vb.mqtt_host);
  vb.mqtt_port     = vbPrefs.getUShort ("mq_port",       vb.mqtt_port);
  vb.mqtt_user     = vbPrefs.getString ("mq_user",       vb.mqtt_user);
  vb.mqtt_pass     = vbPrefs.getString ("mq_pass",       vb.mqtt_pass);
  vb.mqtt_topic    = vbPrefs.getString ("mq_topic",      vb.mqtt_topic);
  vb.pid_kp    = vbPrefs.getFloat  ("pid_kp",    vb.pid_kp);
  vb.pid_ki    = vbPrefs.getFloat  ("pid_ki",    vb.pid_ki);
  vb.pid_kd    = vbPrefs.getFloat  ("pid_kd",    vb.pid_kd);
  vb.pid_tuned = vbPrefs.getBool   ("pid_tun",   vb.pid_tuned);
  for (uint8_t i = 0; i < VBSettings::MAX_SSID; i++) {
    vb.ssid[i] = vbPrefs.getString(("ssid" + String(i)).c_str(), "");
    vb.pass[i] = vbPrefs.getString(("pass" + String(i)).c_str(), "");
  }
  vbPrefs.end();
  // Propagate NVS gains into live globals
  g_pid_kp = vb.pid_kp; g_pid_ki = vb.pid_ki; g_pid_kd = vb.pid_kd;
}

void vb_save() {
  vbPrefs.begin("voltbench", false);
  vbPrefs.putString ("mdns",      vb.mdns);
  vbPrefs.putBool   ("req_login", vb.require_login);
  vbPrefs.putString ("password",  vb.password);
  vbPrefs.putString ("ota_url",   vb.ota_url);
  vbPrefs.putBool   ("ota_ssl",   vb.ota_ssl);
  vbPrefs.putBool   ("ota_auto",  vb.ota_auto);
  vbPrefs.putBool   ("e_current", vb.exp_current);
  vbPrefs.putBool   ("e_fast",    vb.exp_fast);
  vbPrefs.putBool   ("e_smooth",  vb.exp_smooth);
  vbPrefs.putBool   ("e_dial",    vb.exp_dial);
  vbPrefs.putBool   ("g_ocp",     vb.guard_ocp);
  vbPrefs.putBool   ("g_otp",     vb.guard_otp);
  vbPrefs.putUChar  ("g_otp_t",   vb.guard_otp_t);
  vbPrefs.putBool   ("g_rec",     vb.guard_recover);
  for (int i = 0; i < 3; i++) vbPrefs.putFloat(("ilim" + String(i)).c_str(), vb.ilim[i]);
  vbPrefs.putFloat  ("pid_kp",    vb.pid_kp);
  vbPrefs.putFloat  ("pid_ki",    vb.pid_ki);
  vbPrefs.putFloat  ("pid_kd",    vb.pid_kd);
  vbPrefs.putBool   ("pid_tun",   vb.pid_tuned);
  vbPrefs.putBool   ("mq_en",     vb.mqtt_en);
  vbPrefs.putString ("mq_host",   vb.mqtt_host);
  vbPrefs.putUShort ("mq_port",   vb.mqtt_port);
  vbPrefs.putString ("mq_user",   vb.mqtt_user);
  vbPrefs.putString ("mq_pass",   vb.mqtt_pass);
  vbPrefs.putString ("mq_topic",  vb.mqtt_topic);
  vbPrefs.end();
}

void vb_save_wifi_slot(uint8_t i, const String &ssid, const String &pass) {
  if (i >= VBSettings::MAX_SSID) return;
  vb.ssid[i] = ssid; vb.pass[i] = pass;
  vbPrefs.begin("voltbench", false);
  vbPrefs.putString(("ssid" + String(i)).c_str(), ssid);
  vbPrefs.putString(("pass" + String(i)).c_str(), pass);
  vbPrefs.end();
}

bool vb_remember_wifi(const String &ssid, const String &pass) {
  for (uint8_t i = 0; i < VBSettings::MAX_SSID; i++)
    if (vb.ssid[i] == ssid) { vb_save_wifi_slot(i, ssid, pass); return true; }
  for (uint8_t i = 0; i < VBSettings::MAX_SSID; i++)
    if (vb.ssid[i].isEmpty()) { vb_save_wifi_slot(i, ssid, pass); return true; }
  vb_save_wifi_slot(0, ssid, pass);
  return true;
}

void vb_forget_wifi(const String &ssid) {
  for (uint8_t i = 0; i < VBSettings::MAX_SSID; i++)
    if (vb.ssid[i] == ssid) vb_save_wifi_slot(i, "", "");
}

void vb_factory_reset() {
  vbPrefs.begin("voltbench", false);
  vbPrefs.clear();
  vbPrefs.end();
}

// =============================================================================
//   Captive portal AP fallback
// =============================================================================
DNSServer vb_dns;
bool vb_in_captive = false;

bool vb_try_saved_wifi(uint32_t timeout_ms = 12000) {
  for (uint8_t i = 0; i < VBSettings::MAX_SSID; i++) {
    if (vb.ssid[i].isEmpty()) continue;
    WiFi.begin(vb.ssid[i].c_str(), vb.pass[i].c_str());
    uint32_t t0 = millis();
    while (WiFi.status() != WL_CONNECTED && millis() - t0 < timeout_ms) delay(150);
    if (WiFi.status() == WL_CONNECTED) return true;
    WiFi.disconnect();
  }
  return false;
}

void vb_start_captive_ap() {
  WiFi.mode(WIFI_AP_STA);   // STA needed so scanNetworks() still works in AP mode
  String apName = "Voltbench-" + String((uint32_t)ESP.getEfuseMac(), HEX);
  WiFi.softAP(apName.c_str());
  vb_dns.start(53, "*", WiFi.softAPIP());
  vb_in_captive = true;
  Serial.printf("Captive AP: %s @ %s\n", apName.c_str(), WiFi.softAPIP().toString().c_str());
}

// =============================================================================
//   Auth helpers
// =============================================================================
String vb_make_token() {
  String t = "";
  for (int i = 0; i < 4; i++) t += String(esp_random(), HEX);
  return t;
}

bool vb_authed(AsyncWebServerRequest *req) {
  if (!vb.require_login) return true;
  if (req->hasHeader("X-Auth"))
    return req->getHeader("X-Auth")->value() == vb.auth_token;
  return false;
}
#define VB_REQUIRE_AUTH(req) do { if (!vb_authed(req)) { req->send(401, "application/json", "{\"err\":\"auth\"}"); return; } } while (0)

// =============================================================================
//   Guards (over-current / over-temperature)
// =============================================================================
float vb_read_temp_c() { return 35.0f; /* replace with NTC math */ }

float vb_read_current(uint8_t ch) {
  if (ch == 1) return psState.output1 ? 0.08f : 0.0f;
  if (ch == 2) return psState.output2 ? 0.14f : 0.0f;
  if (ch == 3) return psState.output3 ? 0.05f : 0.0f;
  return 0;
}

void vb_trip(uint8_t ch, const char *why) {
  Serial.printf("[guard] CH%u TRIP: %s\n", ch, why);
  vb.trip[ch - 1] = true;
  setOutput(ch, false);
}

uint32_t vb_last_guard = 0;
void vb_guard_tick() {
  if (millis() - vb_last_guard < 100) return;
  vb_last_guard = millis();
  if (vb.guard_otp) {
    float t = vb_read_temp_c();
    if (t > vb.guard_otp_t)
      for (uint8_t ch = 1; ch <= 3; ch++) vb_trip(ch, "OTP");
  }
  if (vb.guard_ocp) {
    for (uint8_t ch = 1; ch <= 3; ch++) {
      if (vb.trip[ch - 1]) continue;
      if (vb_read_current(ch) > vb.ilim[ch - 1]) vb_trip(ch, "OCP");
    }
  }
}

// =============================================================================
//   WebSocket + telemetry broadcast
// =============================================================================
AsyncWebSocket vb_ws("/ws");

void vb_fill_status(JsonDocument &d) {
  d["output1"]  = psState.output1;
  d["output2"]  = psState.output2;
  d["output3"]  = psState.output3;
  // read_VV_volt() = 5-sample rolling average — smoother than raw g_measured_mV
  d["voltage1"] = g_measured_mV / 1000.0f;
  d["voltage2"] = read_5V_volt()  / 1000.0f;
  d["voltage3"] = read_3V3_volt() / 1000.0f;
  d["current1"] = vb_read_current(1);
  d["current2"] = vb_read_current(2);
  d["current3"] = vb_read_current(3);
  d["cc1"]      = vb_read_current(1) > vb.ilim[0] * 0.95f;
  d["cc2"]      = vb_read_current(2) > vb.ilim[1] * 0.95f;
  d["cc3"]      = vb_read_current(3) > vb.ilim[2] * 0.95f;
  d["trip1"]    = vb.trip[0];
  d["trip2"]    = vb.trip[1];
  d["trip3"]    = vb.trip[2];
  d["set1"]     = g_setpoint_mV / 1000.0f;
  d["ts"]       = (uint64_t)millis();
  static const char* const STATE_STR[] = {"idle","settling","running","converged","tuning"};
  d["pid_state"] = STATE_STR[min((uint8_t)4, (uint8_t)g_vctrl_state)];
  d["pid_kp"]    = g_pid_kp;
  d["pid_ki"]    = g_pid_ki;
  d["pid_kd"]    = g_pid_kd;
}

uint32_t vb_last_push = 0;
void vb_push_status() {
  if (vb_ws.count() == 0) return;
  if (millis() - vb_last_push < (vb.exp_fast ? 250 : 1000)) return;
  vb_last_push = millis();
  JsonDocument d;
  vb_fill_status(d);
  String out; serializeJson(d, out);
  vb_ws.textAll(out);
}

void vb_on_ws_event(AsyncWebSocket *srv, AsyncWebSocketClient *c,
                    AwsEventType t, void *arg, uint8_t *data, size_t len) {
  if (t != WS_EVT_DATA) return;
  AwsFrameInfo *fi = (AwsFrameInfo *)arg;
  if (!fi->final || fi->index != 0 || fi->len != len || fi->opcode != WS_TEXT) return;

  JsonDocument doc;
  if (deserializeJson(doc, data, len) != DeserializationError::Ok) return;

  if (vb.require_login) {
    const char *tok = doc["token"];
    if (!tok || String(tok) != vb.auth_token) { c->text("{\"err\":\"auth\"}"); return; }
  }

  const char *action = doc["action"];
  if (!action) return;
  String act = action;
  int    output = doc["output"] | 0;
  float  value  = doc["value"]  | 0.0f;

  if      (act == "toggle" && output >= 1 && output <= 3) {
    bool on = doc["value"].is<bool>() ? doc["value"].as<bool>() : (value >= 0.5f);
    setOutput(output, on);
    vb.trip[output - 1] = false;
  }
  else if (act == "set_voltage" && output == 1)               { setVoltage(value); }
  else if (act == "set_ilimit"  && output >= 1 && output <= 3){ vb.ilim[output-1] = value; vb_save(); }
  else if (act == "all_off")    { setOutput(1,false); setOutput(2,false); setOutput(3,false); }
  else if (act == "clear_trip") { for (int i=0;i<3;i++) vb.trip[i] = false; }

  JsonDocument resp;
  vb_fill_status(resp);
  String out; serializeJson(resp, out);
  c->text(out);
}

// =============================================================================
//   MQTT bridge
// =============================================================================
WiFiClient   vb_mqtt_net;
PubSubClient vb_mqtt(vb_mqtt_net);
uint32_t     vb_last_mqtt = 0;

void vb_mqtt_cmd(char *topic, byte *payload, unsigned int len) {
  String t = topic;
  String p; p.reserve(len);
  for (unsigned i = 0; i < len; i++) p += (char)payload[i];
  String base = vb.mqtt_topic + "/cmd/";
  if (!t.startsWith(base)) return;
  String tail = t.substring(base.length());
  int slash = tail.indexOf('/');
  if (slash < 0) return;
  uint8_t ch = tail.substring(2, slash).toInt();
  String  fn = tail.substring(slash + 1);
  if (fn == "output")                setOutput(ch, p == "on" || p == "1");
  else if (fn == "voltage" && ch==1) setVoltage(p.toFloat());
}

void vb_mqtt_setup() {
  if (!vb.mqtt_en || vb.mqtt_host.isEmpty()) return;
  vb_mqtt.setServer(vb.mqtt_host.c_str(), vb.mqtt_port);
  vb_mqtt.setCallback(vb_mqtt_cmd);
}

void vb_mqtt_loop() {
  if (!vb.mqtt_en || vb.mqtt_host.isEmpty() || vb_in_captive) return;
  if (!vb_mqtt.connected()) {
    if (millis() - vb_last_mqtt < 5000) return;
    vb_last_mqtt = millis();
    String cid = "voltbench-" + String((uint32_t)ESP.getEfuseMac(), HEX);
    bool ok = vb.mqtt_user.isEmpty()
      ? vb_mqtt.connect(cid.c_str())
      : vb_mqtt.connect(cid.c_str(), vb.mqtt_user.c_str(), vb.mqtt_pass.c_str());
    if (ok) {
      vb_mqtt.subscribe((vb.mqtt_topic + "/cmd/#").c_str());
      vb_mqtt.publish ((vb.mqtt_topic + "/status").c_str(), "online", true);
    }
    return;
  }
  vb_mqtt.loop();
  static uint32_t last = 0;
  if (millis() - last > 1000) {
    last = millis();
    JsonDocument d; vb_fill_status(d);
    String out; serializeJson(d, out);
    vb_mqtt.publish((vb.mqtt_topic + "/tele").c_str(), out.c_str());
  }
}

// =============================================================================
//   HTTP routes (/api/* — replaces old /, /control, /status)
// =============================================================================
void vb_register_routes() {

  // Gzipped index
  server.on("/", HTTP_GET, [](AsyncWebServerRequest *req) {
    AsyncWebServerResponse *res =
      req->beginResponse_P(200, "text/html", index_html_gz, index_html_gz_len);
    res->addHeader("Content-Encoding", "gzip");
    res->addHeader("Cache-Control", "public, max-age=300");
    req->send(res);
  });

  server.onNotFound([](AsyncWebServerRequest *req) {
    if (vb_in_captive) { req->redirect("/"); return; }
    req->send(404, "text/plain", "Not found");
  });

  // Status
  server.on("/api/status", HTTP_GET, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    JsonDocument d; vb_fill_status(d);
    String out; serializeJson(d, out);
    req->send(200, "application/json", out);
  });

  // Info
  server.on("/api/info", HTTP_GET, [](AsyncWebServerRequest *req) {
    JsonDocument d;
    d["fw"]            = CURRENT_FIRMWARE_VERSION;
    d["mdns"]          = vb.mdns;
    d["ip"]            = WiFi.localIP().toString();
    d["mac"]           = WiFi.macAddress();
    d["ssid"]          = WiFi.SSID();
    d["rssi"]          = WiFi.RSSI();
    d["uptime"]        = millis() / 1000;
    d["require_login"] = vb.require_login;
    d["captive"]       = vb_in_captive;
    auto ota = d["ota"].to<JsonObject>();
      ota["url"] = vb.ota_url; ota["ssl"] = vb.ota_ssl; ota["auto"] = vb.ota_auto;
    auto exp = d["exp"].to<JsonObject>();
      exp["current"] = vb.exp_current; exp["fast"] = vb.exp_fast;
      exp["smooth"]  = vb.exp_smooth;  exp["dial"]  = vb.exp_dial;
    auto g = d["guard"].to<JsonObject>();
      g["ocp"] = vb.guard_ocp; g["otp"] = vb.guard_otp;
      g["otp_temp"] = vb.guard_otp_t; g["recover"] = vb.guard_recover;
    auto m = d["mqtt"].to<JsonObject>();
      m["enabled"] = vb.mqtt_en; m["host"] = vb.mqtt_host;
      m["port"]    = vb.mqtt_port; m["user"] = vb.mqtt_user;
      m["topic"]   = vb.mqtt_topic;
    auto saved = d["saved_ssids"].to<JsonArray>();
    for (uint8_t i = 0; i < VBSettings::MAX_SSID; i++)
      if (!vb.ssid[i].isEmpty()) saved.add(vb.ssid[i]);
    auto pid = d["pid"].to<JsonObject>();
      pid["kp"] = g_pid_kp; pid["ki"] = g_pid_ki; pid["kd"] = g_pid_kd;
      pid["tuned"] = vb.pid_tuned;
    String out; serializeJson(d, out);
    req->send(200, "application/json", out);
  });

  // Login
  server.on("/api/login", HTTP_POST, [](AsyncWebServerRequest *req) {
    String pass = req->hasParam("pass", true) ? req->getParam("pass", true)->value() : "";
    if (!vb.require_login || pass == vb.password) {
      vb.auth_token = vb_make_token();
      vb_save();
      JsonDocument d; d["ok"] = true; d["token"] = vb.auth_token;
      String out; serializeJson(d, out);
      req->send(200, "application/json", out);
    } else {
      req->send(200, "application/json", "{\"ok\":false,\"err\":\"bad-pass\"}");
    }
  });

  // Control
  server.on("/api/control", HTTP_POST, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    String  action = req->hasParam("action", true) ? req->getParam("action", true)->value() : "";
    uint8_t out    = req->hasParam("output", true) ? req->getParam("output", true)->value().toInt() : 0;
    float   val    = req->hasParam("value",  true) ? req->getParam("value",  true)->value().toFloat() : 0;
    if      (action == "toggle" && out >= 1 && out <= 3) { setOutput(out, val == 1.0f); vb.trip[out-1] = false; }
    else if (action == "set_voltage" && out == 1)        { setVoltage(val); }
    else if (action == "set_ilimit"  && out >= 1 && out <= 3) { vb.ilim[out-1] = val; vb_save(); }
    else if (action == "all_off")    { setOutput(1,false); setOutput(2,false); setOutput(3,false); }
    else if (action == "clear_trip") { for (int i=0;i<3;i++) vb.trip[i] = false; }
    req->send(200, "application/json", "{\"ok\":true}");
  });

  // Settings (JSON body)
  AsyncCallbackJsonWebHandler *settingsHandler =
    new AsyncCallbackJsonWebHandler("/api/settings",
      [](AsyncWebServerRequest *req, JsonVariant &json) {
        if (!vb_authed(req)) { req->send(401); return; }
        JsonObject s = json.as<JsonObject>();
        if (s["mdns"].is<const char*>())     vb.mdns          = s["mdns"].as<String>();
        if (s["require_login"].is<bool>())   vb.require_login = s["require_login"];
        if (s["password"].is<const char*>()) vb.password      = s["password"].as<String>();
        if (s["ota"].is<JsonObject>()) {
          JsonObject o = s["ota"];
          if (o["url"].is<const char*>()) vb.ota_url  = o["url"].as<String>();
          if (o["ssl"].is<bool>())        vb.ota_ssl  = o["ssl"];
          if (o["auto"].is<bool>())       vb.ota_auto = o["auto"];
        }
        if (s["exp"].is<JsonObject>()) {
          JsonObject e = s["exp"];
          if (e["current"].is<bool>()) vb.exp_current = e["current"];
          if (e["fast"]   .is<bool>()) vb.exp_fast    = e["fast"];
          if (e["smooth"] .is<bool>()) vb.exp_smooth  = e["smooth"];
          if (e["dial"]   .is<bool>()) vb.exp_dial    = e["dial"];
        }
        if (s["guard"].is<JsonObject>()) {
          JsonObject g = s["guard"];
          if (g["ocp"].is<bool>())     vb.guard_ocp     = g["ocp"];
          if (g["otp"].is<bool>())     vb.guard_otp     = g["otp"];
          if (g["otp_temp"].is<int>()) vb.guard_otp_t   = g["otp_temp"];
          if (g["recover"].is<bool>()) vb.guard_recover = g["recover"];
        }
        if (s["pid"].is<JsonObject>()) {
          JsonObject p = s["pid"];
          if (p["kp"].is<float>()) { vb.pid_kp = p["kp"]; g_pid_kp = vb.pid_kp; }
          if (p["ki"].is<float>()) { vb.pid_ki = p["ki"]; g_pid_ki = vb.pid_ki; }
          if (p["kd"].is<float>()) { vb.pid_kd = p["kd"]; g_pid_kd = vb.pid_kd; }
        }
        if (s["mqtt"].is<JsonObject>()) {
          JsonObject m = s["mqtt"];
          if (m["enabled"].is<bool>())     vb.mqtt_en   = m["enabled"];
          if (m["host"].is<const char*>()) vb.mqtt_host = m["host"].as<String>();
          if (m["port"].is<int>())         vb.mqtt_port = m["port"];
          if (m["user"].is<const char*>()) vb.mqtt_user = m["user"].as<String>();
          if (m["pass"].is<const char*>()) vb.mqtt_pass = m["pass"].as<String>();
          if (m["topic"].is<const char*>())vb.mqtt_topic= m["topic"].as<String>();
          vb_mqtt_setup();
        }
        vb_save();
        req->send(200, "application/json", "{\"ok\":true}");
      });
  server.addHandler(settingsHandler);

  // PID tune / reset
  server.on("/api/pid/tune", HTTP_POST, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    if (g_vctrl_state == 4) {
      req->send(409, "application/json", "{\"err\":\"already tuning\"}");
      return;
    }
    g_autotune_req = true;
    req->send(200, "application/json", "{\"ok\":true,\"msg\":\"relay tune started\"}");
  });

  server.on("/api/pid/reset", HTTP_POST, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    g_pid_kp = vb.pid_kp = 0.50f;
    g_pid_ki = vb.pid_ki = 0.10f;
    g_pid_kd = vb.pid_kd = 0.02f;
    vb.pid_tuned = false;
    vb_save();
    req->send(200, "application/json", "{\"ok\":true}");
  });

  // Wi-Fi scan
  server.on("/api/wifi/scan", HTTP_GET, [](AsyncWebServerRequest *req) {
    int n = WiFi.scanComplete();
    if (n == WIFI_SCAN_FAILED || n == -2) { WiFi.scanNetworks(true); req->send(202, "application/json", "{\"scanning\":true}"); return; }
    if (n == WIFI_SCAN_RUNNING)            { req->send(202, "application/json", "{\"scanning\":true}"); return; }
    JsonDocument d;
    auto arr = d["networks"].to<JsonArray>();
    for (int i = 0; i < n; i++) {
      auto o = arr.add<JsonObject>();
      o["ssid"] = WiFi.SSID(i);
      o["rssi"] = WiFi.RSSI(i);
      o["sec"]  = WiFi.encryptionType(i) == WIFI_AUTH_OPEN ? "open" : "WPA2";
    }
    String out; serializeJson(d, out);
    req->send(200, "application/json", out);
    WiFi.scanDelete();
    WiFi.scanNetworks(true);
  });

  // Wi-Fi connect
  server.on("/api/wifi/connect", HTTP_POST, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    String ssid = req->hasParam("ssid", true) ? req->getParam("ssid", true)->value() : "";
    String pass = req->hasParam("pass", true) ? req->getParam("pass", true)->value() : "";
    if (ssid.isEmpty()) { req->send(400, "application/json", "{\"err\":\"ssid\"}"); return; }
    vb_remember_wifi(ssid, pass);
    req->send(200, "application/json", "{\"ok\":true}");
    static String s_ssid = ssid, s_pass = pass;
    s_ssid = ssid; s_pass = pass;
    xTaskCreatePinnedToCore([](void*) {
      vTaskDelay(pdMS_TO_TICKS(800));
      WiFi.disconnect();
      WiFi.begin(s_ssid.c_str(), s_pass.c_str());
      vTaskDelete(NULL);
    }, "wifiSwitch", 4096, NULL, 1, NULL, 0);
  });

  // Wi-Fi forget
  server.on("/api/wifi/forget", HTTP_POST, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    if (!req->hasParam("ssid", true)) { req->send(400); return; }
    vb_forget_wifi(req->getParam("ssid", true)->value());
    req->send(200, "application/json", "{\"ok\":true}");
  });

  // OTA
  server.on("/api/ota/check", HTTP_GET, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    req->send(200, "application/json",
      "{\"current\":\"" CURRENT_FIRMWARE_VERSION "\",\"latest\":\"unknown\",\"newer\":false}");
  });
  server.on("/api/ota/update", HTTP_POST, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    req->send(200, "application/json", "{\"ok\":true}");
    extern void perform_ota_tasked();
    perform_ota_tasked();
  });
  server.on("/api/ota/force", HTTP_POST, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    req->send(200, "application/json", "{\"ok\":true}");
    extern void perform_ota_tasked();
    perform_ota_tasked();
  });

  // MQTT test
  server.on("/api/mqtt/test", HTTP_GET, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    if (vb.mqtt_host.isEmpty()) {
      req->send(200, "application/json", "{\"ok\":false,\"err\":\"no broker host configured\"}");
      return;
    }
    WiFiClient c;
    bool ok = c.connect(vb.mqtt_host.c_str(), vb.mqtt_port);
    c.stop();
    req->send(200, "application/json", ok ? "{\"ok\":true}" : "{\"ok\":false,\"err\":\"connect failed\"}");
  });

  // Reboot
  server.on("/api/reboot", HTTP_GET, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    req->send(200, "application/json", "{\"ok\":true}");
    delay(200);
    ESP.restart();
  });

  // Factory reset
  server.on("/api/factory_reset", HTTP_POST, [](AsyncWebServerRequest *req) {
    VB_REQUIRE_AUTH(req);
    vb_factory_reset();
    req->send(200, "application/json", "{\"ok\":true}");
    delay(200);
    ESP.restart();
  });

  // WebSocket
  vb_ws.onEvent(vb_on_ws_event);
  server.addHandler(&vb_ws);
}

// =============================================================================
//   Setup / loop helpers called from the main sketch
// =============================================================================
void vb_on_wifi_event(WiFiEvent_t event) {
  if (event == ARDUINO_EVENT_WIFI_STA_GOT_IP && vb_in_captive) {
    vb_dns.stop();
    WiFi.softAPdisconnect(true);
    WiFi.mode(WIFI_STA);
    vb_in_captive = false;
    MDNS.begin(vb.mdns.c_str());
    Serial.printf("Joined %s — captive AP shut down. IP=%s\n",
                  WiFi.SSID().c_str(), WiFi.localIP().toString().c_str());
  }
}

void vb_setup() {
  vb_load();
  if (vb.auth_token.isEmpty()) { vb.auth_token = vb_make_token(); vb_save(); }
  WiFi.onEvent(vb_on_wifi_event);
  bool wifi_ok = vb_try_saved_wifi();
  if (!wifi_ok) vb_start_captive_ap();
  if (!vb_in_captive) MDNS.begin(vb.mdns.c_str());
  vb_register_routes();
  vb_mqtt_setup();
}

void vb_loop() {
  if (vb_in_captive) vb_dns.processNextRequest();
  static uint32_t lastRetry = 0;
  if (vb_in_captive && millis() - lastRetry > 30000) {
    lastRetry = millis();
    vb_try_saved_wifi(8000);
  }
  vb_guard_tick();
  vb_push_status();
  vb_mqtt_loop();
  vb_ws.cleanupClients();
}
